<?php
	$this->headLink()->appendStylesheet($this->baseUrl().'/js/slider/style.css');
?>

<div id="subconteudo" class="span-24 last">	
	<div class="span-5">
	<div class="span-5 accord">
		<h3><a href="#">PAINEL DE ACESSO</a></h3>
		<div>			
			<div class="span-4">
			Usuário
			<input name="usuario" type="text" id="usuario"/>
			<br>
			Senha
			<input name="senha" type="password" id="senha"/>
			<div id="msgAutenticacao" class="hide erro"></div>
			</div>
			<button class="botao" onclick="autenticar()">Entrar</button>
			<br><br>
			<a href="#">Cadastre-se </a>
			<br>
			<a href="#"> Esqueceu a senha </a>		
		</div>			
	</div>	
	<br><br>
	<div class="clear"><br></div>
	<script src="http://widgets.twimg.com/j/2/widget.js"></script>
	<script> 
		new TWTR.Widget({   
		version: 2,   
		type: 'search',   
		search: '#pendrive',   
		interval: 6000,   
		title: 'TWITTER:',   
		subject: 'pen drive rapido',   
		width: 190,   
		height: 275,   

		theme: {     
			shell: {       
			background: '#9ACD32',       
			color: '#ffffff'     
			},     
			tweets: {       
			background: '#ffffff',    
			   color: '#000000',     
				 links: '#00000'    
				  }   },   
				  features: {    
				   scrollbar: false,    
					loop: true,    
					 live: true,    
					  hashtags: true,    
					   timestamp: true,    
						avatars: true,    
						 behavior: 'default'  
						  }
   }).render().start();
 </script>
	
	</div>
	
	<div class="span-19 last">
	
		<div class="span-19">
			<!-- INTALAR PLUGIN JQUERY -->
			<div class="slider-wrap">
						
				<div id="novidadespdr" class="csw">
					<div class="panelContainer">

						<div class="panel" title="Sucesso PEN DRIVE RAPIDO">
							<div class="wrapper">
								<a href="#">
									<img src="imagens/banner.png" alt="temp" />
								</a>
								<div class="photo-meta-data">
								
									<span>Universidades testam PEN DRIVE RAPIDO e vira sucesso!</span>
								</div>
							</div>
						</div>
						
						<div class="panel" title="faca gratuitamente">
							<div class="wrapper">
								<a href="/cadastro">
									<img src="imagens/banner2.png" alt="temp" />
								</a>
								<div class="photo-meta-data">
									PEN DRIVE RAPIDO SEM CUSTOS<br />
									<span>Como seu pen drive convencional com a diferenca do preco!</span>
								</div>
							</div>
						</div>		
						
						<div class="panel" title="PDR FLEXIVEL">	
							<div class="wrapper">
								<img src="imagens/banner3.png" alt="scotch egg" class="floatLeft"/>	
								
							</div>
						</div>

					</div>
				</div>
				
				
				<!-- PEQUENOS -->
				
				<div id="movers-row">
					<div>
						<a href="#1" class="cross-link active-thumb">
						<img src="imagens/peq1.jpg" class="nav-thumb" alt="temp-thumb" />
						</a>
					</div>
				
					<div><a href="#2" class="cross-link"><img src="imagens/peq2.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>
					<div><a href="#3" class="cross-link"><img src="imagens/peq3.jpg" class="nav-thumb" alt="temp-thumb" /></a></div>
				</div>
							
								
			</div>
		</div>		
		
		<div class="clear"><br><br><br><br></div>
		<hr>
		
		<div class="span-19" style="color:#000">
		   <div class="span-9 border">
				<div class="span-3">
				<img src="<?php echo $this->baseUrl();?>/imagens/seguro.png"></img>
				</div>
				<div class="span-4">
				<b style="color:#000; font-size:10px">TEXTOS INFERIORES</b>
				<br>
					Aliquam cursus interdum purus at eleifend. 
					Ut viverra accumsan velit eget interdum. 
					Cras mattis placerat eleifend. 
					Proin luctus, est quis ullamcorper eleifend, magna mi vestibulum libero, non accumsan nibh nunc et nisi.
					Nam tempor nisi turpis.
				</div>
			
		   </div>
		   <div class="span-9">
				<div class="span-3">
				<img src="<?php echo $this->baseUrl();?>/imagens/flexisivel.png"></img>
				</div>
				<div class="span-4">
				<b style="color:#000; font-size:10px">TEXTOS INFERIORES</b>
				<br>
					Aliquam cursus interdum purus at eleifend. 
					Ut viverra accumsan velit eget interdum. 
					Cras mattis placerat eleifend. 
					Proin luctus, est quis ullamcorper eleifend, magna mi vestibulum libero, non accumsan nibh nunc et nisi.
					Nam tempor nisi turpis.
				</div>
		   </div>
		</div>
	
		<div class="clear"><br></div>
	<div class="span-20">
		<br><br>
		<b style="font-size:40px; color:#000">
		<a href="#">
		<img src="http://www.ving-xa.com/images/banner.jpg" title="EXEMPLO DE BANNER DE PROPAGANDA" />
		</a>
		
		</b>
	</div>

		<div class="clear"><br></div>
		
		
	</div>
	
		
</div>
	
<?php 
$this->headScript()->appendFile($this->baseUrl().'/js/slider/jquery-easing-1.3.pack.js');
$this->headScript()->appendFile($this->baseUrl().'/js/slider/jquery-easing-compatibility.1.2.pack.js');
$this->headScript()->appendFile($this->baseUrl().'/js/slider/coda-slider.1.1.1.pack.js');
$this->headScript()->appendFile($this->baseUrl().'/js/views/index/index.js');

?>

<script>
	
var theInt = null;
var $crosslink, $navthumb;
var curclicked = 0;
		
theInterval = function(cur){
	clearInterval(theInt);
	
	if( typeof cur != 'undefined' )
		curclicked = cur;
	
	$crosslink.removeClass("active-thumb");
	$navthumb.eq(curclicked).parent().addClass("active-thumb");
		$(".stripNav ul li a").eq(curclicked).trigger('click');
	
	theInt = setInterval(function(){
		$crosslink.removeClass("active-thumb");
		$navthumb.eq(curclicked).parent().addClass("active-thumb");
		$(".stripNav ul li a").eq(curclicked).trigger('click');
		curclicked++;
		if( 6 == curclicked )
			curclicked = 0;
		
	}, 3000);
};
		
$(function(){
	
	$("#novidadespdr").codaSlider();
	
	$navthumb = $(".nav-thumb");
	$crosslink = $(".cross-link");
	
	$navthumb
	.click(function() {
		var $this = $(this);
		theInterval($this.parent().attr('href').slice(1) - 1);
		return false;
	});
	
	theInterval();
});

</script>



