<div id="subconteudo" class="span-24 last">	
	<div id="subconteudo" class="span-24 last">	
		<div class="span-5 accord">
			<h3><a href="#">Informativo</a></h3>
			<div>
				<p>	Lorem ipsum dolor sit amet, consectetur adipiscing elit.	
					Vivamus euismod quam vel risus luctus aliquam. Proin quis dolor mauris, 
					non tincidunt tellus. Sed sagittis justo vel ipsum auctor sit amet adipiscing est vehicula. 
					Suspendisse vel tellus at quam luctus ultrices. Nulla elit augue, tempus dignissim congue ac, 
					posuere vel eros. Proin cursus adipiscing sagittis. Nullam et sem nibh.
				</p>
			</div>			
		</div>
		<div class="span-19 last">
			<div id="novo" class="span-19 last">				
				<div id="novoPendrive" class="tab span-19 last">
					<ul>
						<li><a href="#divFormNovoPendrive">Novo Pendrive</a></li>
					</ul>
					<div id="divFormNovoPendrive">
						<form id="formNovoPendrive" action="">
							<div class="span-3 pretop-5">Nome</div>
							<div class="span-15 last">
								<input type="text" name="nome" id="nome" size="50"></input>
							</div>
							<div class="span-3 pretop-5">Email</div>
							<div class="span-15 last">
								<input type="text" name="email" id="email" size="50" onBlur="checkEmail(this)" onFocus="limpaImg(this)"></input>
								<img id="loadEmail" class="hide" src="<?php echo $this->baseUrl();?>/imagens/mini-loader.gif"/>
							</div>
							<div class="span-3 pretop-5">Apelido</div>
							<div class="span-15 last">
								<input type="text" name="apelido" id="apelido" onBlur="checkApelido(this)" onFocus="limpaImg(this)"></input>
								<img id="loadApelido" class="hide" src="<?php echo $this->baseUrl();?>/imagens/mini-loader.gif"/>
							</div>
							<div class="span-3 pretop-5">Senha</div>
							<div class="span-15 last">
								<input type="text" name="senha" id="senha"></input>
							</div>
							<div class="span-3 pretop-5">Confirmação de Senha</div>
							<div class="span-15 last">
								<input type="text" name="confirSenha" id="confirSenha"></input>
							</div>					
							<div class="span-3"></div>					
							<input type="submit" value="Criar Pendrive" class="botao" id="criar"></input>
						</form>
						<div id="msgFormNovoPendrive" class="hide span-18 last"></div>
					</div>
			 	</div>		 	
			</div>				
		</div>	
	</div>
	<?php 
		$this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.validate.js');
		$this->headScript()->appendFile($this->baseUrl().'/js/views/pendrive/cadastro.js');
	?>
</div>