<?php //echo $this->doctype() ?>
<!-- <html xmlns="http://www.w3.org/1999/xhtml"> -->
<!DOCTUPE HTML>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Pendrive Rápido</title>
<?php 
	$this->headLink()->appendStylesheet($this->baseUrl().'/jquery/jquery-ui/themes/start/jquery.ui.all.css');
	$this->headLink()->appendStylesheet($this->baseUrl().'/blueprint/screen.css');
	$this->headLink()->appendStylesheet($this->baseUrl().'/css/estilo.css');	 
	echo $this->headLink(); 
	
	$this->headScript()->prependFile($this->baseUrl().'/js/layout.js');
	$this->headScript()->prependFile($this->baseUrl().'/js/Helper.js');
	$this->headScript()->prependFile($this->baseUrl().'/js/jAjax.js');	
	$this->headScript()->prependFile($this->baseUrl().'/jquery/jquery-ui/ui/jquery.ui.accordion.js');
	$this->headScript()->prependFile($this->baseUrl().'/jquery/jquery-ui/ui/jquery.ui.tabs.js');
	$this->headScript()->prependFile($this->baseUrl().'/jquery/jquery-ui/ui/jquery.ui.button.js');
	$this->headScript()->prependFile($this->baseUrl().'/jquery/jquery-ui/ui/jquery.ui.widget.js');
	$this->headScript()->prependFile($this->baseUrl().'/jquery/jquery-ui/ui/jquery.ui.core.js');
	$this->headScript()->prependFile($this->baseUrl().'/jquery/jquery.js');	
	echo $this->headScript();

?>	

 <link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/imagens/favicon.ico" type="image/x-icon"/>	
</head>
<body>
	<div id="container" class="container">
		<!-- TOPO -->
		<br>
		<header>
			<div class="span-10">
				<img src="<?php echo $this->baseUrl();?>/imagens/logo_pendriverapido.png" width="400" height="115"></img>	
			</div>
			
			<div class="span-13">
				<div class="span-13">
					<ul class="menuprincipal">
						<li><a href="/index"> PRINCIPAL </a></li>
						<li><a href="<?php echo $this->baseUrl();?>/pendrive/cadastro"> CADASTRO </a></li>
						<li><a href="#"> SOBRE </a></li>
						<li><a href="#"> CONTATO </a></li>
					</ul>
				</div>
				<div class="clear"><br><br></div>
				
				<div class="span-13 push-2"> 
					<b style="font-size:28px; color:#48ADE3; font-family:'Comic Sans MS', cursive;">O seu dispositivo fácil</b> 
				</div>
				
				<div class="span-13"> 
					<div class="push-11">
					<img src="<?php echo $this->baseUrl();?>/imagens/pdr_seta.png" ></img>
					</div>
				</div>

			</div>
		</header>
		
		<!-- FIM TOPO -->

		<!-- CONTEUDO -->
		<div id="conteudo" class="span-24 last">			
			<?php echo $this->layout()->content; ?>
		</div>
		<!-- FIM CONTEUDO -->
		
		
		<div class="clear">
			<br>
		</div>
	<!-- RODAPÉ -->
	<footer>
		<div id="rodape">
		 <br>
			<div class="span-24">
				<div class="span-5">
					<b style="color:#fff"> PEN DRIVE RAPIDO 2011 </b>
					<br><br>
					PROJETO UNIVERSITÁRIO DE CONCLUSÃO DE CURSO
					<br>
				</div>
				<div class="span-18">
					<a href="#"> Sobre </a> 
					<br>
					<a href="#" title="entre em contato"> Contato </a>
				</div>	
				
			</div>
			<div class="clear"></div>
		</div>
	</footer>
											
	</div>

</body>
</html>